### ISSUE TITLE
Can't receive messages from mqtt

### ISSUE THREAD

**Issue by faronov** [mhaas/mqtt-to-influxdb-forwarder#3]
Hi
I have messages in mqtt
like
MQTT publish: topic 'zigbee2mqtt/0x00158d0002465164', payload '{"temperature":26.42,"linkquality":68,"humidity":36.14,"battery":91,"voltage":2985}'

and try to subscribe to this topic using forwared.py with  --node-name zigbee2mqtt
but didn't receive any message that can be forwarded to influxdb
verbose mode won't help understand what's wrong
INFO:forwarder.MQTTSource:Connected with result code  0
INFO:forwarder.MQTTSource:Subscribing to topic /zigbee2mqtt/# for node_name zigbee2mqtt

what's can be wrong, and how to find the problem?
mqtt without user and password

python forwarder.py --mqtt-host mqtt --influx-host influxdb --influx-user user --influx-pass-file pass --influx-db sensors --node-name zigbee2mqtt --verbose

I use mosquitto as mqtt server
maybe it must be configured for allowing wildcard # ?

**Comment by mhaas** [comment]
Hi,

I believe the code assumes that your Matt topic starts with a slash '/', but yours does not. You can try patching the code to remove the slash!

**Comment by faronov** [comment]
Thank you!

this really help, now I can receive messages
but have another issue
this topic seems to send only state (like online or offline)
can I handle this inside forwarder?

DEBUG:forwarder.MQTTSource:Received MQTT message for topic zigbee2mqtt/bridge/state with payload online
Traceback (most recent call last):
  File "forwarder.py", line 192, in <module>
    main()
  File "forwarder.py", line 189, in main
    source.start()
  File "forwarder.py", line 155, in start
    self.client.loop_forever()
  File "/usr/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 1378, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 897, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 1177, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 1766, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 2239, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 2414, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 2574, in _handle_on_message
    self.on_message(self, self._userdata, message)
  File "forwarder.py", line 134, in on_message
    if measurement_name in self.stringify:
TypeError: argument of type 'NoneType' is not iterable

**Comment by faronov** [comment]
looks like --stringify-values-for-measurements online
is the right way how to handle such string

**Comment by faronov** [comment]
Thanks for this forwarder
